---
Name: 'googletagmanager'
---
Page:
  extensions:
    - Bigfork\SilverStripeGoogleTagManager\Extension\PageExtension
SiteConfig:
  extensions:
    - Bigfork\SilverStripeGoogleTagManager\Extension\SiteConfigExtension
