---
Name: 'googletagmanager'
---
Page:
  extensions:
    - Bigfork\SilverStripeGoogleTagManager\Extension\PageExtension
SiteConfig:
  extensions:
    - Bigfork\SilverStripeGoogleTagManager\Extension\SiteConfigExtension
---
Name: 'googletagmanagerrequestprocessors'
Before:
  - '#requestprocessors'
---
Injector:
  RequestProcessor:
    properties:
      filters:
        - '%$Bigfork\SilverStripeGoogleTagManager\Control\RequestFilter'
