---
Name: googletagmanagerconfig
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - 'Bigfork\SilverStripeGoogleTagManager\Extension\PageExtension'
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - 'Bigfork\SilverStripeGoogleTagManager\Extension\SiteConfigExtension'
---
Name: googletagmanagermiddleware
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        GoogleTagManagerMiddleware: '%$Bigfork\SilverStripeGoogleTagManager\Control\GoogleTagManagerMiddleware'
